# Generated by Django 2.1 on 2018-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('recipe_name', models.CharField(max_length=255)),
                ('meal_id', models.IntegerField(choices=[(1, 'Lunch'), (2, 'Dinner')])),
            ],
        ),
    ]
